### ISSUE TITLE
update rustc 1.20.0-nightly (d84693b93 2017-07-09)  to  complie error

### ISSUE THREAD

**Issue by suyanlong** [danburkert/capnp-nonblock#2]
error[E0425]: cannot find function `allocate` in module `heap`
   --> /home/room/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/capnp-nonblock-0.3.0/src/buf.rs:187:31
    |
187 |             let bytes = heap::allocate(len, refcount_len);
    |                               ^^^^^^^^ not found in `heap`

error[E0425]: cannot find function `oom` in module `alloc`
   --> /home/room/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/capnp-nonblock-0.3.0/src/buf.rs:188:50
    |
188 |             if bytes == ptr::null_mut() { alloc::oom() }
    |                                                  ^^^ not found in `alloc`

error[E0425]: cannot find function `deallocate` in module `heap`
   --> /home/room/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/capnp-nonblock-0.3.0/src/buf.rs:226:23
    |
226 |                 heap::deallocate(allocation, self.len + refcount_len, refcount_len);
    |                       ^^^^^^^^^^ not found in `heap`

error: use of unstable library feature 'allocator_api': the precise API and guarantees it provides may be tweaked slightly, especially to possibly take into account the types being stored to make room for a future tracing garbage collector (see issue #32838)
 --> /home/room/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/capnp-nonblock-0.3.0/src/buf.rs:1:19
  |
1 | use alloc::{self, heap};
  |                   ^^^^
  |
  = help: add #![feature(allocator_api)] to the crate attributes to enable

**Comment by danburkert** [comment]
Hey @suyanlong, apologies for not (yet) updating the README, but this crate has effectively been retired.  If you want to submit a PR I'd gladly accept it, but I probably won't be putting in the effort to fix the compilation error (I think the allocator API is somewhat unstable at the moment anyway).  You most likely want to look in to https://github.com/capnproto/capnp-futures-rs for the replacement.

**Comment by suyanlong** [comment]
ok, thank you ,

**Comment by suyanlong** [comment]
@danburkert   ok, thank you ,
